### PR TITLE
Text representation of QTableView

### PR DESCRIPTION
**Pull request by vladimir-kraus**

### CODE REVIEW

**Comment by hekra01** [comment]
@vladimir-kraus thanks

**Comment by vladimir-kraus** [comment]
I am afraid that this merge request was sent by mistake. I meant to create this merge request for this commit only: https://github.com/cisco-open-source/qtwebdriver/pull/63/commits/bf55dd27778433d87f3d11b770cd02a95ca1d8ae 

**I suggest to revert these changes** as most of the changes are not correct or relevant for the public usage of QtWebDriver. They are only relevant within our local environment. Sorry for the mistake.

**Comment by kk6ho** [comment]
Any status on the fix or reversion of this PR? I can confirm that since this merge, my build is breaking.

**Comment by hekra01** [comment]
done: 161780d3e816fc9dd52ad1af3933f0ecd77e05bd

**Pull request merged**
